# RAG 参数调测平台 - 基础配置
# 适用于快速启动和测试

services:
  # 后端服务
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: rage-backend
    restart: unless-stopped
    environment:
      - ENV_FILE=/app/.env
      - DATABASE_URL=sqlite:///./rage.db
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    volumes:
      - ../backend/uploads:/app/uploads
      - ../backend/logs:/app/logs
      - ../backend/.env:/app/.env:ro
      - backend_data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      milvus:
        condition: service_healthy
    networks:
      - rage-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: builder # 使用构建阶段
    container_name: rage-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - rage-network
    # 使用简单的静态文件服务器
    command: ["npx", "serve", "-s", "dist", "-l", "5173"]

  # Milvus 向量数据库
  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: rage-milvus
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - COMMON_STORAGETYPE=local
      - COMMON_SECURITY_AUTHORIZATIONENABLED=false
      - LOG_LEVEL=info
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      - rage-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

volumes:
  backend_data:
    driver: local
  milvus_data:
    driver: local

networks:
  rage-network:
    driver: bridge
